# Generated by Django 4.2 on 2026-02-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_brand_item_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("produce", "Produce"),
                    ("dairy", "Dairy"),
                    ("meat", "Meat & Poultry"),
                    ("bakery", "Bakery"),
                    ("canned", "Canned Goods"),
                    ("frozen", "Frozen"),
                    ("pantry", "Pantry Staples"),
                    ("beverages", "Beverages"),
                    ("snacks", "Snacks"),
                    ("condiments", "Condiments & Sauces"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
