# Generated by Django 4.2 on 2026-02-09 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_item_quantity"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserItem",
            new_name="UserItemQuantity",
        ),
        migrations.AlterField(
            model_name="item",
            name="users",
            field=models.ManyToManyField(
                related_name="items",
                through="api.UserItemQuantity",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
