# Generated by Django 4.2 on 2026-02-10 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


DEFAULT_LOCATIONS = ["Pantry", "Fridge", "Freezer", "Kitchen Counter"]


def create_locations_and_assign(apps, schema_editor):
    User = apps.get_model("api", "CustomUser")
    Location = apps.get_model("api", "Location")
    UserItemQuantity = apps.get_model("api", "UserItemQuantity")

    for user in User.objects.all():
        for name in DEFAULT_LOCATIONS:
            Location.objects.get_or_create(user=user, name=name)

    for user_item in UserItemQuantity.objects.filter(location__isnull=True):
        pantry = Location.objects.get_or_create(user=user_item.user, name="Pantry")[0]
        user_item.location = pantry
        user_item.save(update_fields=["location"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_useritemquantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="useritemquantity",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_items",
                to="api.location",
            ),
        ),
        migrations.RunPython(create_locations_and_assign, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="useritemquantity",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_items",
                to="api.location",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useritemquantity",
            unique_together={("user", "item", "location")},
        ),
    ]
